---
deployment:
  tasks:
    - export REPOPATH=/home/kedaipar/repositories/eventpariban1
    - export DEPLOYPATH=/home/kedaipar/public_html
    - cd "$REPOPATH" && composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
    - cd "$REPOPATH" && php artisan migrate --force
    - /bin/cp -R "$REPOPATH/public/." "$DEPLOYPATH/"
    - /bin/cp "$REPOPATH/cpanel/index.php" "$DEPLOYPATH/index.php"
